## Cropping images with ROI method then using pytesseract to make it as a text 


In [1]:
import cv2
import numpy as np

In [2]:
 #image_path
img_path="pan_card.jpg"

#read image
img_raw = cv2.imread(img_path)
#resize image
#img_raw = cv2.resize(img_raw, (600, 600))#resize image if you need when region does't fit crop it


In [3]:
#select ROIs function
ROIs = cv2.selectROIs("Select Rois",img_raw)

#print rectangle points of selected roi
print(ROIs)

#Crop selected roi ffrom raw image

#counter to save image with different name
crop_number=0 

[[  8  78 210  50]
 [ 14 225 205  61]
 [ 19 173 165  41]
 [ 14 129 230  40]]


In [4]:
#loop over every bounding box save in array "ROIs"
for rect in ROIs:
    x1=rect[0]
    y1=rect[1]
    x2=rect[2]
    y2=rect[3]

        #crop roi from original image
    img_crop=img_raw[y1:y1+y2,x1:x1+x2]

        #show cropped image
    cv2.imshow("crop"+str(crop_number),img_crop)

#save cropped image
    cv2.imwrite("crop"+str(crop_number)+".jpeg",img_crop)
        
    crop_number+=1

#hold window
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
import cv2 
import pytesseract

#it's important to locate the file where the ocr software as been installed else Pytesseract shows like not installed or unable to locate the path
pytesseract.pytesseract.tesseract_cmd=r'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'

In [6]:
img_1 = cv2.imread('crop0.jpeg')
text_1=pytesseract.image_to_string(img_1)

In [9]:
img_2 = cv2.imread('crop1.jpeg')
text_2=pytesseract.image_to_string(img_2)
img_3 = cv2.imread('crop2.jpeg')
text_3=pytesseract.image_to_string(img_3)
img_4 = cv2.imread('crop3.jpeg')
text_4=pytesseract.image_to_string(img_4)

In [10]:
print(text_1,text_2,text_3,text_4)

RAHUL GUPTA
 ABCDE1234F
 23/11/1974
 SURESH GUPTA



In [11]:
df=[text_1,text_2,text_3,text_4] #saving the text has  as dataframe

In [12]:
import pandas as pd

In [13]:
dict =[text_1,text_2,text_3,text_4]
     
df = pd.DataFrame(dict)
  
# saving the dataframe
df.to_csv('pan.csv')

In [15]:
df #you can edit the dataframe by creating a spreate col for name,last name and pan mumber

0
0   RAHUL GUPTA\n

1    ABCDE1234F\n

2    23/11/1974\n

3  SURESH GUPTA\n